/********************************************* Disclaimer *********************************************/
/* This file is generated by aiecompiler . */
/* Changes to this file may cause incorrect behavior and will be lost if aiecompiler is invoked again.*/

#include <iostream>
#include "adf/adf_api/AIEControlConfig.h"


/************************** Graph Configurations  *****************************/

  adf::GraphConfig GraphConfigurations[] = {
  //{id, name, graphLoadElfFunc, graphInitFunc, graphDebugHalt, coreColumns, coreRows, iterMemColumns, iterMemRows, iterMemAddrs, triggered, plKernelInstanceNames, plAxiLiteModes, plDriverStartFuncs, plDriverCheckIPDoneFuncs}
    {0, "gr", nullptr, nullptr, nullptr, {8}, {0}, {8}, {1}, {0x4404}, {0}, {}, {}, {}, {},  }, 
  };
  const int NUM_GRAPH = 1;


/************************** RTP Configurations  *****************************/

  adf::RTPConfig RTPConfigurations[] = {
  //{portId, aliasId, portName, aliasName, graphId, isInput, isAsync, isConnect, elemType, numBytes, isPL, hasLock, blocking , isSlaveRTP, selectorColumn, selectorRow, selectorAddr, selectorLockId, pingColumn, pingRow, pingAddr, pongColumn, pongRow, pongAddr, pongLockId, plKernelInstanceName, plParameterIndex, plDriverWriteRTP, plDriverReadRTP}
    {3, 0, "gr.k.in[1]", "gr.value", 0, true, false, false, (adf::RTPConfig::elementType)4, 4, false, true, true, false, 8, 1, 0x3fe0, 2, 8, 0, 0, 0, 8, 0, 0x4000, 1, "", -1, nullptr, nullptr},
  };
  const int NUM_RTP = 1;

/************************** PLIO Configurations  *****************************/

  adf::PLIOConfig PLIOConfigurations[] = {
  //{id, name, loginal_name, shim_column, slaveOrMaster, streamId}
    {0, "gr.plio_in", "din0", 8, 0, 0},
    {1, "gr.plio_out", "dout0", 8, 1, 0},
  };
  const int NUM_PLIO = 2;


/************************** ADF API initializer *****************************/

  class InitializeAIEControlXRT
  {
  public:
    InitializeAIEControlXRT()
    {
      std::cout<<"Initializing ADF API..."<<std::endl;
#ifdef __EXCLUDE_PL_CONTROL__
      bool exclude_pl_control = true;
#else
      bool exclude_pl_control = false;
#endif
      adf::initializeConfigurations(nullptr, 0, 0, 0,
                                    GraphConfigurations, NUM_GRAPH,
                                    RTPConfigurations, NUM_RTP,
                                    nullptr, 0,
                                    nullptr, 0,
                                    nullptr, 0,
                                    nullptr, 0,
                                    nullptr, 0,
                                    nullptr, 0,
                                    nullptr, 0,
                                    PLIOConfigurations, NUM_PLIO,
                                    nullptr, 0, 0, nullptr,
                                    false, exclude_pl_control, false, nullptr,
                                    true, 0, 2);

    }
  } initAIEControlXRT;


  using namespace adf;

// Kernel Stub Definition
  template<int32 num> void vect_add(adf::input_buffer<int32, adf::extents<num>> &__restrict in, adf::output_buffer<int32, adf::extents<num>> &__restrict out, int32 value) { /* Stub */ } 
  template void vect_add<256>(adf::io_buffer<int, adf::direction::in, adf::io_buffer_config<adf::extents<256>>> &__restrict,adf::io_buffer<int, adf::direction::out, adf::io_buffer_config<adf::extents<256>>> &__restrict,int); /* explicit template instantiation */ 
